export const GAME_CONSTANTS = {
  DEFAULT_ROUND_DURATION_SEC: 60,
  DEFAULT_TOTAL_ROUNDS: 8,
  STARTING_MONEY: 10000, // represent as integer (e.g. 10,000 tỷ VNĐ)
  MIN_TEAMS: 2,
  MAX_TEAMS: 9,
  QUIZ_DURATION_SEC: 30,
  ROUND_RESULTS_DURATION_SEC: 8,
  EVENT_DURATION_SEC: 5,
  NARRATION_DURATION_SEC: 6,
  COUNTDOWN_DURATION_SEC: 5,
} as const;
